name: Generate GitHub Snake Animation

on:
  # Executa a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  # Permite que você execute este fluxo de trabalho manualmente na guia Ações
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      # Necessário para que a action possa fazer commit do arquivo SVG gerado no seu repositório
      contents: write
    steps:
      # Faz o checkout do seu repositório para que a action possa acessá-lo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Gera a animação da cobrinha
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          # Seu nome de usuário do GitHub (ou o nome da organização)
          github_user_name: ${{ github.repository_owner }}
          
          # Lista de arquivos de saída e suas configurações
          # Este aqui gera o arquivo 'github-snake-dark.svg' na pasta 'dist' com o tema escuro do GitHub
          outputs: dist/github-snake-dark.svg?palette=github-dark

      # Faz o commit do arquivo SVG gerado de volta para o seu repositório
      - name: Commit and Push Snake SVG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-snake-dark.svg
          # Verifica se há alterações para commitar
          if git diff --staged --quiet; then
            echo "Snake animation SVG is already up-to-date."
          else
            git commit -m "chore: update github snake animation"
            git push
          fi
